### ISSUE TITLE
Any chance implement the same functionality in browser extension?

### ISSUE THREAD

**Issue by kolulu23** [kasusa/me_in_jandan#1]
使用浏览器扩展实现短期帖子/回帖的存储和查询会大幅增强部分用户的体验。
请问技术上实现是否可行？

我的想法：
- 保存当前帖子内容->静态html
- 保存常用id+邮箱组合->回复/发帖时纪录id，如`/t/5236777`
  - 由于删帖或超时删除的可能，提供两种保存模式：链接 or 静态快照
- 对保存内容的全文搜索

> 我对浏览器扩展的了解有限，不知道它是否可以调用本地存储的api，或者暂存在浏览器存储。
> 我知道油猴上可能会有类似的脚本，但一个独立的浏览器扩展在维护和扩展性上显然更胜一筹。

话题之外我想说，上述的扩展功能也许会造成评论区口水量增加，这也是为什么我有些犹豫要实现这个idea

**Comment by kasusa** [comment]
保存的话我觉得是个好主意。
回帖查询也可以列上日程。
但…可能会产生对小破站相当于ddos攻击一样的大量访问……
更重要的是，我不会写浏览器扩展 XD
ps:
发帖时记录id不知道怎么做，我昨天实验了一下，发帖的时候没有显示id呀，要审核之后才会有。

**Comment by kolulu23** [comment]
> 但…可能会产生对小破站相当于ddos攻击一样的大量访问……

不要background请求，相当于从浏览器渲染完的DOM中找到数据，煎蛋没有很多动态脚本，浏览器扩展采集的只有用户所见的数据，这个过程可以做成惰性的。

> 更重要的是，我不会写浏览器扩展 XD

我对浏览器扩展的了解也有限，不过今天看到你发的帖子感觉可以做一做，我最近比较有时间，应该可以帮上忙。:D

> 发帖时记录id不知道怎么做
其实我的意思是保存回帖时那条帖子的id，这样用户可以回过头来手动查询。同样地，这个过程完全是惰性的，不需要引入通知机制或者后台任务。

静态快照，chrome可以保存MTHML，不知道有没有对扩展提供好用的api，但我的确搜到了“保存当前tab页”的chrome扩展。

**Comment by kasusa** [comment]
我主要想弄成这个样子：
1. 通过pyscript把他变成一个网页，优化手机的界面，这样就可以轻松在手机上看到自己发的帖子了，并且不需要装插件（因为如果有电脑我虽然麻烦些也可以用F3，手机上是完全不能搜索）。
2. 在web上可以预览当前的帖子（如树洞、无聊图的第一张图）

目前看来，你的提议主要是增加查看自己回复过帖子的功能（保存的功能先放一边），
通过方式是在回复的同时，通过浏览器插件，记录回复的主贴id

但是这个功能有两个不好实现的地方：
1. 回帖的界面是有不一样的页面结构设计的（应该）不能复用现在的部分代码了
2. 回复时候记录帖子id，需要通过浏览器插件，我还不会弄

> 其实我还是不想弄成插件的样子，不过如果到时候网页做出来了转换成插件应该不会很难弄，可以作为一个比较后期的计划

- ps 放假啦我要玩游戏去
- pss 为啥我收不到你回复我issue的通知

**Comment by kolulu23** [comment]
这几天我会试着探索下浏览器扩展的点子，如果有进展我会更新（也有可能在另外的repo）。


> * pss 为啥我收不到你回复我issue的通知

可能是Notification设置的关系吧。
@kasusa

**Comment by kolulu23** [comment]
@kasusa Hello, 我还是选择去搞扩展去了，而且感觉可以存不少内容，在用户本地存个几十万帖子不成问题haha，[ScrambledEgg](https://github.com/kolulu23/ScrambledEgg)
